# ---------------------------------------------
# Build static assets
# ---------------------------------------------
FROM node:8.12 as assets

COPY *.js* ./
COPY fala/assets-src ./fala/assets-src
RUN npm install
RUN ./node_modules/.bin/gulp build --production

# ---------------------------------------------
# Configure Nginx 
# ---------------------------------------------
FROM nginx:1.14-alpine
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY --from=assets ./fala/assets/ /home/static

EXPOSE 80
