# Dockerfile for running playwright on CircleCi and locally

# Use the Playwright image as the base image
FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

# Create a non-root user and group with a unique UID
RUN groupadd -r appgroup && useradd -r -u 1010 -g appgroup -m -d /home/app appuser

# Install Python dependencies for testing
RUN pip install playwright pytest pytest-playwright

# Make a new directory outside to isolate and copy the playwright repo content.
RUN mkdir /fala_playwright
WORKDIR /fala_playwright

# Copy only the Playwright tests
COPY ./playwright /fala_playwright

# Ensure proper permissions
RUN chown -R appuser:appgroup /fala_playwright

# Switch to the non-root user
USER appuser

# Expose any ports if needed (example: 8000)
EXPOSE 8000

# Command to run the Playwright tests
CMD ["pytest"]
