apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kubernetes.io/change-cause: "<to be filled in deploy_to_kubernetes script>"
  name: laa-fala-collect-static-cronjob
spec:
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: laa-fala-collect-static
          labels:
            app: laa-fala
            tier: collect-static
            type: job
            env: production
        spec:
          restartPolicy: Never
          serviceAccountName: laa-fala-production-irsa-sevice-account
          containers:
          - name: app
            image: "<to be set by deploy_to_kubernetes>"
            command: ["/home/app/docker/collect_static.sh"]
            env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn
            - name: STATIC_FILES_BACKEND
              value: s3
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3
                  key: bucket_name
