{
 "title": "LAA CLA / FALA",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, namespace)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(container_memory_usage_bytes{namespace='$namespace'})",
     "legendFormat": "POD: {{ pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{namespace='$namespace'}[5m]))",
     "legendFormat": "POD: {{ pod_name}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Requested (soft limit)"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{namespace='$namespace'})",
     "legendFormat": "Limit (hard limit)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='$namespace'}[5m]))))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}