apiVersion: apps/v1
kind: Deployment
metadata:
  name: laa-fala
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laa-fala-app
  template:
    metadata:
      labels:
        app: laa-fala-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/fala:main
        name: app
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep","10"]
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 250Mi
        env:
        - name: ALLOWED_HOSTS
          value: ".laa-fala-production.apps.live-1.cloud-platform.service.justice.gov.uk .find-legal-advice.justice.gov.uk"
        - name: GOOGLE_MAPS_API_KEY
          value: AIzaSyC3yE4iqalLcys8ZbjdZAPjDpcYuwd2GME
        - name: LAALAA_API_HOST
          value: https://laa-legal-adviser-api-production.cloud-platform.service.justice.gov.uk
        - name: ENVIRONMENT
          value: production
        - name: DJANGO_SETTINGS_MODULE
          value: "fala.settings.production"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: dsn
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: SECRET_KEY
        - name: FEATURE_FLAG_NO_MAP
          value: "false"
        - name: FEATURE_FLAG_SURVEY_MONKEY
          value: "false"
