apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laa-fala
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laa-fala-app
  template:
    metadata:
      labels:
        app: laa-fala-app
    spec:
      containers:
      - image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-fala-webapp:master
        name: webapp
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ALLOWED_HOSTS
          value: ".laa-fala-production.apps.cloud-platform-live-0.k8s.integration.dsd.io .find-legal-advice.justice.gov.uk"
        - name: LAALAA_API_HOST
          value: https://prod.laalaa.dsd.io
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: dsn
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: SECRET_KEY
        - name: ZENDESK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: zendesk-api
              key: ZENDESK_API_TOKEN
        - name: ZENDESK_API_USERNAME
          valueFrom:
            secretKeyRef:
              name: zendesk-api
              key: ZENDESK_API_USERNAME
        - name: GA_ID
          valueFrom:
            secretKeyRef:
              name: ga-id
              key: GA_ID
      - image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/laa-get-access/laa-fala-nginx:master
        name: nginx
        readinessProbe:
          httpGet:
            path: /static/ping.json
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /static/ping.json
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: http
