apiVersion: apps/v1
kind: Deployment
metadata:
  name: laa-fala
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laa-fala-app
  template:
    metadata:
      labels:
        app: laa-fala-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/fala:master
        name: app
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep","10"]
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ALLOWED_HOSTS
          value: ".laa-fala-production.apps.live.cloud-platform.service.justice.gov.uk .find-legal-advice.justice.gov.uk"
        - name: GOOGLE_MAPS_API_KEY
          value: AIzaSyC3yE4iqalLcys8ZbjdZAPjDpcYuwd2GME
        - name: LAALAA_API_HOST
          value: https://laa-legal-adviser-api-production.cloud-platform.service.justice.gov.uk
        - name: ENVIRONMENT
          value: production
        - name: GA_ID
          value: "UA-37377084-6"
        - name: DJANGO_SETTINGS_MODULE
          value: "fala.settings.production"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: dsn
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: SECRET_KEY
        - name: ZENDESK_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: zendesk-api
              key: ZENDESK_API_TOKEN
        - name: ZENDESK_API_USERNAME
          valueFrom:
            secretKeyRef:
              name: zendesk-api
              key: ZENDESK_API_USERNAME
        - name: STATIC_FILES_BACKEND
          value: s3
        - name: AWS_STORAGE_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: s3
              key: bucket_name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3
              key: secret_access_key
        - name: AWS_S3_REGION_NAME
          valueFrom:
            secretKeyRef:
              name: s3
              key: region
