#!/bin/sh -e
safe_git_branch=${CIRCLE_BRANCH//\//-}
short_sha="$(git rev-parse --short=7 $CIRCLE_SHA1)"
ECR_DEPLOY_IMAGE="$ECR_DOCKER_REPO_BASE:$safe_git_branch.$short_sha"
export IMAGE_TAG="$safe_git_branch"

if [ "$CIRCLE_BRANCH" == "master" ]; then
  export TARGET_TAGS="$safe_git_branch.$short_sha,$safe_git_branch,$CIRCLE_SHA1"
else
  export TARGET_TAGS="$safe_git_branch.$short_sha,$safe_git_branch"
fi
