#!/bin/sh -e

source $(dirname "$0")/define_build_environment_variables
environment="$1"

github_repo_url="${CIRCLE_REPOSITORY_URL//git@github.com:/https://github.com/}"
github_repo_url="${github_repo_url//.git/}"

cat <<END > payload.json
{
  "text": ":tada: Deployed \`${github_repo_url}/commit/$short_sha\` to *$environment*.",
  "attachments": [
    {
      "fallback": "<$CIRCLE_BUILD_URL|View build>",
      "actions": [{"type": "button", "text": "View build", "url": "$CIRCLE_BUILD_URL"}]
    }
  ]
}
END

curl --request POST --data @payload.json --header "Content-Type: application/json" $SLACK_WEBHOOK_URL
