---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fala
  namespace: laa-fala-production
spec:
  secretName: fala-tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'find-legal-advice.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'find-legal-advice.justice.gov.uk'
      dns01:
        provider: route53-dsd
