apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laa-fala
  namespace: laa-fala-staging
spec:
  tls:
  - hosts:
    - laa-fala-staging.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: laa-fala-staging.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: laa-fala
          servicePort: 80
