apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: laa-fala
  namespace: laa-fala-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-fala-laa-fala-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  tls:
  - hosts:
    - laa-fala-staging.apps.live.cloud-platform.service.justice.gov.uk
  - hosts:
    - staging.find-legal-advice.justice.gov.uk
    secretName: fala-tls-certificate
  rules:
  - host: laa-fala-staging.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific   
        backend:
          service:
            name: laa-fala
            port:
              number: 80
  - host: staging.find-legal-advice.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: laa-fala
            port:
              number: 80
