apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-run-migrations
  namespace: laa-fala-staging
spec:
  template:
    spec:
      containers:
      - name: create-and-migrate
        image:  754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-access/fala:main
        command: ["/bin/bash", "-c", "/home/app/fala/migrate_db.sh"]
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: rds-postgresql-instance-output
              key: database_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: rds-postgresql-instance-output
              key: database_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-postgresql-instance-output
              key: database_password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: rds-postgresql-instance-output
              key: rds_instance_address
        - name: DB_PORT
          value: "5432"
        resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 125Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      restartPolicy: Never
      automountServiceAccountToken: false
